#!/bin/bash
gcc -g -o bin/task_4_c code/main.c code/input.c code/inrnd.c code/output.c
time ./bin/task_4_c -n 10000 ./tests/rnd01_out_01.txt ./tests/rnd01_out_02.txt
time ./bin/task_4_c -f ./tests/test01.txt ./tests/test01_out_01.txt ./tests/test01_out_02.txt
time ./bin/task_4_c -f ./tests/test02.txt ./tests/test02_out_01.txt ./tests/test02_out_02.txt
time ./bin/task_4_c -f ./tests/test03.txt ./tests/test03_out_01.txt ./tests/test03_out_02.txt
time ./bin/task_4_c -f ./tests/test04.txt ./tests/test04_out_01.txt ./tests/test04_out_02.txt
time ./bin/task_4_c -f ./tests/test05.txt ./tests/test05_out_01.txt ./tests/test05_out_02.txt
